image:
  repository: postgres
  tag: "13"
  pullPolicy: IfNotPresent

postgresUser: udaconnect
postgresPassword: udaconnect
postgresDb: udaconnect

service:
  type: ClusterIP
  port: 5432
imagePullSecrets: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  DATABASE_URL: postgresql://udaconnect:udaconnect@postgres:5432/udaconnect
