replicaCount: 1
image:
  repository: yasminkloub1994/udaconnect-kafka-consumer
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000
imagePullSecrets: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  DATABASE_URL: postgresql://udaconnect:udaconnect@postgres:5432/udaconnect
  KAFKA_BOOTSTRAP_SERVERS: udaconnect-kafka:9092
command:
  - python
  - -u
  - controller.py
