# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location_connection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'location_connection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19location_connection.proto\x12\x0b\x63onnections\"6\n\x0fLocationRequest\x12\x11\n\tperson_id\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x05\"M\n\x0cNearbyPerson\x12\x11\n\tperson_id\x18\x01 \x01(\t\x12\x13\n\x0blocation_id\x18\x02 \x01(\t\x12\x15\n\rcreation_time\x18\x03 \x01(\t2]\n\x0fLocationService\x12J\n\x0fGetNearbyPeople\x12\x1c.connections.LocationRequest\x1a\x19.connections.NearbyPersonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_connection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONREQUEST']._serialized_start=42
  _globals['_LOCATIONREQUEST']._serialized_end=96
  _globals['_NEARBYPERSON']._serialized_start=98
  _globals['_NEARBYPERSON']._serialized_end=175
  _globals['_LOCATIONSERVICE']._serialized_start=177
  _globals['_LOCATIONSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
