apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connections
  namespace: argocd
spec:
  destination:
    namespace: udaconnect
    server: https://kubernetes.default.svc
  source:
    path: kubernetes/helm/connections
    repoURL: https://github.com/Yasmin-Abdel-Latif/UdaConnect.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
