apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-u", "controller.py"]
          env:
            - name: DATABASE_URL
              value: "postgresql://udaconnect:udaconnect@postgres:5432/udaconnect"
            - name: LOG_LEVEL
              value: "info"
            - name: FLASK_APP
              value: "controller.py"
            - name: PYTHONUNBUFFERED
              value: "1"
